### ISSUE TITLE
"Select contest" causes Visual Studio to crash.

### ISSUE THREAD

**Issue by joseph-hlucny-umd** [antofik/codeforces#9]
Earlier today, I was able to use the Select contest feature. But now when I press the button (with the solution from git clone https://github.com/antofik/codeforces.git open), it freezes Visual Studio and eventually crashes.

Does anyone know what might be causing this? Let me know if you need any more information.

![1](https://user-images.githubusercontent.com/35283117/67615138-e707ac80-f78d-11e9-8629-ff911c1f4e00.png)
![2](https://user-images.githubusercontent.com/35283117/67615139-e707ac80-f78d-11e9-907e-88086b946e49.png)

**Comment by antofik** [comment]
Probably something changed on codeforces side. I will check

**Comment by joseph-hlucny** [comment]
It appears to be working again!
